### ISSUE TITLE
propertyChange does not work for textChanges

### ISSUE THREAD

**Issue by cindy-m** [EddyVerbruggen/nativescript-numeric-keyboard#10]
in the normal textfields, it is possible to use propertiesChange or ngModelChange to apply a function for every keyboardbuttonpress the user applies (set in the html). 
example code:
 <TextField  #mytextField
                   keyboardType="number"
                   [text]="myText"
                   (propertyChange)="onTextChange($event)"
                   hint="test field"></TextField>
For specific constraints, I need this functionality. My constraints are working perfectly until I add the numerickeyboard with decorate. 
Is it possible to get this working again? 
By The way, this is only when updateTextTrigger is set to textChange. If it is set to focusLost, it actually fires the function declared in propertyChange as wished.

**Comment by EddyVerbruggen** [comment]
Did you talk to Maurice about this? We discussed this extensively.

**Comment by cindy-m** [comment]
Yes, we also tries it out. He said that it was working in a precious version and also found it weird that it isn't working anymore.

He also tried it a few times ;)

**Comment by toddanglin** [comment]
This may be related to changes in NativeScript 3.0 (assuming that's the version of NativeScript you're using). See this Issue: https://github.com/NativeScript/NativeScript/issues/3971

You probably need to bind to the `textChange` event instead of the `propertyChange` event to make this work in 3.0. Hope that helps.
