### ISSUE TITLE
App doesn't build 

### ISSUE THREAD

**Issue by iMarwan-k** [EddyVerbruggen/nativescript-numeric-keyboard#32]
Hi Eddy, 

I'm getting the following error when I build the app

ERROR in node_modules/nativescript-numeric-keyboard/numeric-keyboard.ios.d.ts(28,79): error TS2304: Cannot find name 'MMNumberKeyboardDelegate'.
node_modules/nativescript-numeric-keyboard/numeric-keyboard.ios.d.ts(30,20): error TS2304: Cannot find name 'MMNumberKeyboardDelegate'.
node_modules/nativescript-numeric-keyboard/numeric-keyboard.ios.d.ts(38,42): error TS2304: Cannot find name 'MMNumberKeyboard'.

Everything was working good, but I needed to do "npm i" then I started to get this error

After looking more into it, it seems like this issue not exist on 4.2.2 version, and it somehow connected with the pod file

Thanks

**Comment by diegobelfiore** [comment]
Hi,

I'm getting the same error using Vue:

[Vue warn]: Error in nextTick: "TypeError: Could not load view for: nativenumerickeyboard. ReferenceError: Can't find variable: MMNumberKeyboardDelegate"

Everything works in the simulator for iPhone/iPad, but not on an actual device.

**Comment by elonmallin** [comment]
I get the same error when I do `import { NumericKeyboard } from 'nativescript-numeric-keyboard';`.

**Comment by EddyVerbruggen** [comment]
Share a repo folks.. it's hard to give any decent advice without looking at your code/setup.

**Comment by diegobelfiore** [comment]
Hi Eddy,

I have a [sample repo here](https://github.com/diegobelfiore/nskeyboarddemo). All the action is in [App.vue](https://github.com/diegobelfiore/nskeyboarddemo/blob/master/src/App.vue). This works in the simulator for me, but not on my phone (npm run preview:ios).

Also, any idea why the comma doesn't work on Android? I have the input localized to it-IT where the decimal separator is ',' but nothing happens when I press the comma in the android simulator. Only the period works, but it's not the correct decimal separator for the region.

In the iOS simulator, the correct decimal operator for the region comes up with the keyboard and works when I use it to enter something like a currency value.

**Comment by EddyVerbruggen** [comment]
The Preview app doesn’t support this plugin. Try tns run ios instead.

**Comment by diegobelfiore** [comment]
Yup, that was it: tns run ios/android works.

Any idea why the comma decimal separator doesn't work on android? I have locale="it_IT" set for the input, and I switched my device to use the keyboard localized to Italian, but no luck. 

The comma button is available in the android simulator, but nothing happens when you press it. On a physical device the comma button is disabled and only the period is available.

**Comment by KevinBeckers** [comment]
Same issue after updating to nativescript 6.0. Both `tns run ios` and `tns run android` fails with:

```
ERROR in node_modules/nativescript-numeric-keyboard/numeric-keyboard.ios.d.ts(28,79): error TS2304: Cannot find name 'MMNumberKeyboardDelegate'.
node_modules/nativescript-numeric-keyboard/numeric-keyboard.ios.d.ts(30,20): error TS2304: Cannot find name 'MMNumberKeyboardDelegate'.
node_modules/nativescript-numeric-keyboard/numeric-keyboard.ios.d.ts(38,42): error TS2304: Cannot find name 'MMNumberKeyboard'.
```

**Comment by EddyVerbruggen** [comment]
Try doing a `pod repo update` on your dev machine and make sure you're not running this plugin inside the Preview app. If anyone still has issues, create a repo with a demo and ping me there.

**Comment by KevinBeckers** [comment]
Tried `pod repo update`. Didn't fix the issue for me. I will try to create a repo this week as this issue is in a personal project.

**Comment by diegobelfiore** [comment]
Looks like decimal input is an [unresolved issue with NativeScript](https://discourse.nativescript.org/t/allow-decimalchar-insted/3506/3) on Android.

I also tried using a plain TextField with keyboardType="number" but the comma separator does nothing on Android, even if you change the device locale to a region like it-IT or nl-NL.

**Comment by KevinBeckers** [comment]
It seems that `import { NumericKeyboard } from "nativescript-numeric-keyboard";` causes the error. I created a test repo here: https://github.com/KevinBeckers/nativescript-numeric-keyboard-test
