### ISSUE TITLE
Decimal separator issues

### ISSUE THREAD

**Issue by mdassen** [EddyVerbruggen/nativescript-numeric-keyboard#6]
1 Still allows multiple decimal separators when none exist yet.
2 Does not allow any decimal separators when the existing decimal separator is deleted, while this should be possible.

**Comment by EddyVerbruggen** [comment]
Do you perhaps have a field where also thousand-separators are shown? I can imagine those may break the logic in this plugin.

**Comment by EddyVerbruggen** [comment]
Also relevant to know: do you use `decorate` or `NumericKeyboardView`?

**Comment by EddyVerbruggen** [comment]
Please reopen with your answers in case 2.1.4 doesn't fix it.

**Comment by EddyVerbruggen** [comment]
For anyone else wondering, we've figured it out: the OP used the plugin as follows on an Angular app:

```js
<NumericKeyboard updateTextTrigger="focusLost"></NumericKeyboard>
```

The `updateTextTrigger` directive with value `focusLost` means the textfield model isn't updated until the focus is lost, so the logic to look for duplicate decimals is never triggered.

Once [this PR](https://github.com/NativeScript/NativeScript/pull/3896) is merged into NativeScript we can use the `blur` event instead of `updateTextTrigger` which will allow the plugin to limit the number of decimals to 1 automatically.

So if you're reading this and `blur` is not available yet and you need `updateTextTrigger="focusLost"` for some reason, then use plugin version 2.1.1.
